### ISSUE TITLE
Big Thank you

### ISSUE THREAD

**Issue by ghost** [dhinakg/vm-rpc#6]
Hey, I normally don't do this and I feel like it is a bit rude to do this in an issue, but I don't know how I could thank you either.
This is basically directly the solution I needed, I wanted to show what VM I'm working on in Workstation without people needing to ask me, and having it all here is a nice thing.
There's not really a lot I can say, thank you for the repository though, even if the last release was made in October.
Might as well add that I had no issues with the 0.5.0 release and everything has been running smoothly.

I'll immediately close the issue since it's not an issue.

**Comment by dhinakg** [comment]
Kind words are always appreciated. :smile: 
I want to release a project I have in the works first, but after I am planning on making updates to this.

**Comment by ghost** [comment]
Yeah, it does what it does best, so don't let some small project distract you from something serious.
Thank you for vmrpc though, exactly the thing I searched and wanted ❤️
